// @ts-check
import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';

// The site is served from a project page, so everything lives under /docs.
// Declared once: the `base` option and the link rewriter below must never
// disagree, and two string literals eventually do.
const base = '/docs';

/**
 * Prefix root-absolute links written in Markdown with the base path.
 *
 * Starlight prefixes the links it generates itself — sidebar, pagination,
 * breadcrumbs — because it builds them from slugs. A link an author types into
 * a page is emitted verbatim, so `[x](/concepts/guards/)` would 404 under a
 * base path. Measured on this site before the rewriter existed: 28 broken
 * links against 23 working ones, with no error at build time.
 *
 * Fixing it in the source instead would mean writing `/docs/...` in every
 * page — the base hardcoded into the content, breaking again the day it moves,
 * and one more thing for a contributor to remember and forget.
 *
 * Only `<a href>` is touched. Images and other assets in Markdown are resolved
 * by Astro itself; this exists solely for links the author wrote by hand.
 */
function rehypeBasePrefix() {
	return (tree) => {
		const visit = (node) => {
			if (node.type === 'element' && node.tagName === 'a') {
				const href = node.properties?.href;

				// Root-absolute only. Anchors, relative paths, external URLs and
				// protocol-relative URLs are already correct, and prefixing a link
				// that is already prefixed would produce /docs/docs/…
				if (
					typeof href === 'string' &&
					href.startsWith('/') &&
					!href.startsWith('//') &&
					href !== base &&
					!href.startsWith(base + '/')
				) {
					node.properties.href = base + href;
				}
			}

			node.children?.forEach(visit);
		};

		visit(tree);
	};
}

// The sidebar is written out by hand rather than autogenerated. Reading order
// matters here: someone meeting nit for the first time has to understand what a
// filtered projection is before anything else makes sense, and alphabetical
// order would bury that behind "Architecture".
export default defineConfig({
	site: 'https://nitscm.github.io',
	base,

	markdown: {
		rehypePlugins: [rehypeBasePrefix],
	},

	integrations: [
		starlight({
			title: 'nit',
			// The site's palette and type, so the three surfaces a reader
			// crosses are the same product rather than three that share a name.
			customCss: ['./src/styles/theme.css'],

			// Dark unless the reader has said otherwise. See the component for
			// why it is a fork rather than a wrapper, and how "auto" stays honest.
			components: { ThemeProvider: './src/components/ThemeProvider.astro' },
			description:
				'An authorization layer between developers and a git forge. Per-file read and write control, on any repository.',

			social: [
				{ icon: 'github', label: 'GitHub', href: 'https://github.com/NitScm/nit' },
			],

			editLink: {
				baseUrl: 'https://github.com/NitScm/docs/edit/main/',
			},

			lastUpdated: true,

			sidebar: [
				{
					label: 'Start here',
					items: [
						{ label: 'What nit does', slug: 'start/what-nit-does' },
						{ label: 'Install', slug: 'start/install' },
						{ label: 'Your first workspace', slug: 'start/first-steps' },
						{ label: 'Your first policy', slug: 'start/first-policy' },
					],
				},
				{
					label: 'Concepts',
					items: [
						{ label: 'Filtered projections', slug: 'concepts/filtered-projections' },
						{ label: 'The authorization model', slug: 'concepts/authorization' },
						{ label: 'Guards', slug: 'concepts/guards' },
						{ label: 'Push and pull', slug: 'concepts/push-and-pull' },
						{ label: 'Architecture', slug: 'concepts/architecture' },
						{ label: 'Glossary', slug: 'concepts/glossary' },
					],
				},
				{
					label: 'Guides',
					items: [
						{ label: 'Writing a policy bundle', slug: 'guides/policy-bundles' },
						{ label: 'Policy for a large organisation', slug: 'guides/policy-at-scale' },
						{ label: 'Configuring the server', slug: 'guides/server' },
						{ label: 'Running workers', slug: 'guides/workers' },
						{ label: 'Connecting a forge', slug: 'guides/forges' },
						{ label: 'The web console', slug: 'guides/console' },
						{ label: 'Day-to-day operations', slug: 'guides/operations' },
						{ label: 'Going to production', slug: 'guides/production' },
						{ label: 'Example: GitHub over SSH', slug: 'guides/example-github-ssh' },
					],
				},
				{
					// The commercial edition, in the same site as everything else.
					//
					// A separate one would leak the open-core line page by page: it
					// would be a catalogue of what the free edition does not do.
					// Here each piece sits next to the thing it extends, and a
					// reader who is not buying can see what it is instead of
					// wondering.
					label: 'Enterprise',
					items: [
						{ label: 'What it is for', slug: 'enterprise' },
						{ label: 'The audit vault', slug: 'enterprise/audit-vault' },
						{ label: 'Checking it yourself', slug: 'enterprise/checking-it-yourself' },
						{ label: 'Retention and legal hold', slug: 'enterprise/retention' },
						{ label: 'People and access', slug: 'enterprise/access' },
						{ label: 'Running it at scale', slug: 'enterprise/at-scale' },
						{ label: 'Seeing it work', slug: 'enterprise/try-it' },
					],
				},
				{
					label: 'Reference',
					items: [
						{ label: 'nit — the developer CLI', slug: 'reference/nit' },
						{ label: 'nitctl — the operator CLI', slug: 'reference/nitctl' },
						{ label: 'Configuration settings', slug: 'reference/configuration' },
						{ label: 'The HTTP API', slug: 'reference/api' },
						{ label: 'Error codes', slug: 'reference/errors' },
					],
				},
			],
		}),
	],
});
