// @ts-check
import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';

// The sidebar is written out by hand rather than autogenerated. Reading order
// matters here: someone meeting nit for the first time has to understand what a
// filtered projection is before anything else makes sense, and alphabetical
// order would bury that behind "Architecture".
export default defineConfig({
	site: 'https://nitscm.github.io',

	integrations: [
		starlight({
			title: 'nit',
			description:
				'An authorization layer between developers and a git forge. Per-file read and write control, on any repository.',

			social: [
				{ icon: 'github', label: 'GitHub', href: 'https://github.com/NitScm/nit' },
			],

			editLink: {
				baseUrl: 'https://github.com/NitScm/nit-docs/edit/main/',
			},

			lastUpdated: true,

			sidebar: [
				{
					label: 'Start here',
					items: [
						{ label: 'What nit does', slug: 'start/what-nit-does' },
						{ label: 'Install', slug: 'start/install' },
						{ label: 'Your first workspace', slug: 'start/first-steps' },
						{ label: 'Your first policy', slug: 'start/first-policy' },
					],
				},
				{
					label: 'Concepts',
					items: [
						{ label: 'Filtered projections', slug: 'concepts/filtered-projections' },
						{ label: 'The authorization model', slug: 'concepts/authorization' },
						{ label: 'Guards', slug: 'concepts/guards' },
						{ label: 'Push and pull', slug: 'concepts/push-and-pull' },
						{ label: 'Architecture', slug: 'concepts/architecture' },
						{ label: 'Glossary', slug: 'concepts/glossary' },
					],
				},
				{
					label: 'Guides',
					items: [
						{ label: 'Writing a policy bundle', slug: 'guides/policy-bundles' },
						{ label: 'Configuring the server', slug: 'guides/server' },
						{ label: 'Running workers', slug: 'guides/workers' },
						{ label: 'Connecting a forge', slug: 'guides/forges' },
						{ label: 'The web console', slug: 'guides/console' },
						{ label: 'Day-to-day operations', slug: 'guides/operations' },
						{ label: 'Going to production', slug: 'guides/production' },
						{ label: 'Example: GitHub over SSH', slug: 'guides/example-github-ssh' },
					],
				},
				{
					label: 'Reference',
					items: [
						{ label: 'nit — the developer CLI', slug: 'reference/nit' },
						{ label: 'nitctl — the operator CLI', slug: 'reference/nitctl' },
						{ label: 'Configuration settings', slug: 'reference/configuration' },
						{ label: 'The HTTP API', slug: 'reference/api' },
						{ label: 'Error codes', slug: 'reference/errors' },
					],
				},
			],
		}),
	],
});
